ALTER TABLE `applicationdomain`.`accounts` 
ADD COLUMN `credit` DECIMAL(10,0) NOT NULL AFTER `subcategoryId`,
ADD COLUMN `debit` DECIMAL(10,0) NOT NULL AFTER `credit`,
ADD COLUMN `comment` VARCHAR(200) NULL AFTER `debit`,
ADD COLUMN `dateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `comment`,
ADD COLUMN `dateModified` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP AFTER `dateAdded`;