INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (2, 'Salaries Payable');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (1, 'Accounts Receivable');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (1, 'Supplies');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (1, 'Office Equipment');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (5, 'Contributed Capital');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (1, 'Prepaid Rent');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (1, 'Prepaid Insurance');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (2, 'Unearned Revenue');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (2, 'Accounts Payable');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (4, 'Advertising Expense');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (3, 'Service Revenue');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (4, 'Salaries Expense');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (4, 'Telephone Expense');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (4, 'Utilities Expense');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (4, 'Insurance Expense');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (4, 'Depreciation Expense');
INSERT INTO `applicationdomain`.`subcategories` (`CategoryId`, `Name`) VALUES (1, 'Accumulated Depreciation');
